### ISSUE TITLE
Unable to search for a line further behind in the tail

### ISSUE THREAD

**Issue by spacer59** [victor9000/log-search#4]
Tried searching for a keyword present `/var/log/api.log`. It is far behind the last line. I was unable to search for it
```
root@1de4533895db:/app# curl 'http://172.16.238.15:8000/search?phrase=97001114' | jq
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   141  100   141    0     0   1023      0 --:--:-- --:--:-- --:--:--  1029
{
  "results": [
    "__NO_MATCHES__"
  ],
  "next_page_url": "http://172.16.238.15:8000/search?file_name=&phrase=97001114&max_lines=25&skip_bytes=48323576"
}
```

**Comment by spacer59** [comment]
Looks like it short circuits at `max_bytes=10000000` maybe that's why, closing.

**Comment by victor9000** [comment]
Yes, this gets at how pagination works.  `__NO_MATCHES__` means that the algorithm started at `EOF` and searched backwards over `max_bytes=10000000` for the token but could not find it.  The UI then uses `next_page_url` to search the next "page".  So during the next invocation, the algorithm will search backwards again, but this time from `skip_bytes=48323576` (as opposed to from `EOF`) to look for the token.  This means that the file is searched in chunks and the UI can display very large result sets without hanging on any single request.

Having said all that, this assumes that you're able to access the UI, but if you're not able to due to the issues discussed in #1 then I can update the API with different default values.  I'll follow up when this is done.

**Comment by victor9000** [comment]
For context, you can see how this is used in the UI in the link below:
https://youtu.be/01NWgSaSd70

**Comment by spacer59** [comment]
gotcha, that makes sense but why is skip_bytes > max_bytes?

**Comment by victor9000** [comment]
`skip_bytes` is effectively a jump position within the file, while max_bytes is the number of bytes to search after we've made the jump.  Meaning that `skip_bytes` is an absolute value while `max_bytes` is a relative value.  

So for example, let's say we're processing a 2TB file, we may have a value of `skip_bytes=1.9TB` and `max_bytes=1GB`.  This would say skip over the first 1.9TB of the file and search backwards (towards the beginning of the file) from that position, but only search for 1GB.  So in most cases skip_bytes will be greater than max_bytes.

**Comment by spacer59** [comment]
Right but the first call where skip_bytes is not specified, should it not equal max_bytes in the next url? I'd expect it to stop searching at max_bytes and make that the offset i.e skip_bytes.

**Comment by victor9000** [comment]
To clarify, `max_bytes` is a constant value since this represents the chunk interval.  So if we want to process in larger or smaller chunks then we can adjust this value.  `skip_bytes` on the other hand, is a variable value that represents the starting point for processing from the BOF position.  So a small `skip_bytes` value will mean that we're going to start processing closer to the beginning of the file, and a large one means closer to the end.

If we were searching in the forward direction then we could set `skip_bytes` to `max_bytes` after the first call as you described, and every future `skip_bytes` would just be a multiple of `max_bytes`.  But we're searching in the backwards direction so it's a little more tricky.

During the first call where `skip_bytes` is not set, we seek to `EOF` (since we have to process the file backwards), so we effectively have a `skip_bytes` that equals the entire file since we skipped to the very end.  From there we process a chunk equal to `max_bytes` and we calculate a new `skip_bytes` value of `EOF - max_bytes`.  The new `skip_bytes` will represent how much of the file we skip over, starting from BOF, before we start processing backwards again.

So after the first call, we would calculate the `skip_bytes` for the next call as follows: 
```
                   <------ processing ------
 0                                                  2TB
 |---------------------------------------------------|
BOF                             |                   EOF
                                |----- max_bytes ----|
                                |
                            skip_bytes = EOF - max_bytes
```

**Comment by spacer59** [comment]
gotcha that makes sense 👍, was thinking skip_bytes from back of file.

**Comment by victor9000** [comment]
Another reason for calculating skip_bytes from BOF is that the log file is not a static asset, meaning that it will grow continuously.  So basing the offset from the EOF position will result in double processing as new records are added and the EOF position gets pushed further and further back.

There's an update in place now that will use larger chunks for the REST api than for the Web Socket UI requests.  This means we can optimize for latency on UI requests while increasing the search space for REST requests.  So you should be able to find the `97001114` token in a single request now.

Also this update change the central sync file to `/var/log/sync.log`

**Comment by spacer59** [comment]
Cool, that's a good point.
